version: '2'

services:
  app:
    build: .
    image: sam-blog
    command: amber watch
    environment:
      AMBER_ENV: development
      BLOG_PASSWORD: ${BLOG_PASSWORD}
    ports:
      - 3000:3000
    links:
      - db
    volumes:
    - .:/app
    - nodes:/app/node_modules
    - shards:/app/lib

  migrate:
    build: .
    image: sam-blog
    command: bash -c 'while ! nc -q 1 db 5432 </dev/null; do sleep 1; done && amber db migrate seed'
    volumes:
      - .:/app
    links:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sam_blog_development
    volumes:
      - db:/var/lib/postgres/data

volumes:
  db:
  nodes:
  shards: