version: '2'

services:
  app:
    build:
      context: .
      dockerfile: DockerfileProd
    image: sam-blog-prod
    command: bin/sam-blog
    environment:
      AMBER_ENV: production
      DATABASE_URL: postgres://admin:password@db:5432/sam_blog
      BLOG_PASSWORD: ${BLOG_PASSWORD}
    ports:
      - 80:80
    links:
      - db
    volumes:
    - .:/app
    - nodes-prod:/app/node_modules
    - shards-prod:/app/lib

  migrate:
    build:
      context: .
      dockerfile: DockerfileProd
    image: sam-blog-prod
    command: bash -c 'while ! nc -q 1 db 5432 </dev/null; do sleep 1; done'
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/sam_blog
    volumes:
      - .:/app
    links:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sam_blog
    volumes:
      - db-prod:/var/lib/postgres/data

volumes:
  db-prod:
  nodes-prod:
  shards-prod: