version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: sam-blog-prod
    command: bin/sam-blog
    environment:
      AMBER_ENV: production
      BLOG_PASSWORD: ${BLOG_PASSWORD}
    ports:
      - 80:80
    links:
      - db

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: sam-blog-prod
    command: bash -c 'while ! nc -q 1 db 5432 </dev/null; do sleep 1; done && amber db migrate'
    environment:
      AMBER_ENV: production
    links:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sam_blog
    volumes:
      - db:/var/lib/postgres/data

volumes:
  db: